name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '1.8'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Show build artifact (debug)
        run: |
          echo "Listing build/libs:"
          ls -la build/libs || true
          echo "If no jar appears above, Gradle did not create the artifact."

      - name: Show .dockerignore (debug)
        run: |
          if [ -f .dockerignore ]; then
            echo ".dockerignore contents:"
            cat .dockerignore
          else
            echo "No .dockerignore file found"
          fi

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: master-${{ github.sha }}
          dockerfile: Dockerfile
          build-args: |
            JAR_PATH=build/libs
